import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import  {Navbar}  from "@/components/component/nav-bar";
import Footer from "@/components/component/footer";
import Background from "@/components/component/background";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "LI JAR | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "min-h-screen bg-background relative font-sans antialiased",
          fontSans.variable
        )}
      >
        <Background />
        <div className="relative z-10">
          <Navbar/>
          <div className="py-10 pb-[200px]">{children}</div>
          <div className="mt-10 absolute inset-x-0 bottom-0"><Footer/></div>
        </div>
      </body>
    </html>
  );
}
